name: dart_package
description: An example Dart package created with very_good_cli
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.2.1
  test: ^1.19.2
  very_good_analysis: ^3.0.1
